import Head from "next/head";
import { Inter } from "next/font/google";
import { useState } from "react";
import TextInput from "@/components/TextInput";
import SubmitButton from "@/components/SubmitButton";
import ResponseDisplay from "@/components/ResponseDisplay";
import useApi from "@/hooks/useApi";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [inputValue, setInputValue] = useState("");
  const [topic, setTopic] = useState("poam");
  const [submitValue, setSubmitValue] = useState("");
  const [userMessages, setUserMessages] = useState([]);
  const [assistantMessages, setAssistantMessages] = useState([]);
  const { data, error, loading } = useApi(
    "/api/openai",
    "POST",
    submitValue,
    userMessages,
    assistantMessages
  );

  const handleSubmit = (event) => {
    event.preventDefault();
    setSubmitValue(inputValue);
    setUserMessages([...userMessages, inputValue]);

    if (data?.result) {
      setAssistantMessages([...assistantMessages, data.result]);
    }
  };

  const handleInputChange = (event) => {
    setInputValue(event.target.value);
  };

  return (
    <>
      <Head>
        <title>NextJS OpenAI Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <div className="form-container">
          <h1 className={inter.className}>Tweet Generator 🚀</h1>
          <form>
            <ResponseDisplay data={data} error={error} loading={loading} />
            <TextInput
              value={inputValue}
              onChange={handleInputChange}
              suggention={topic}
            />
            <SubmitButton onClick={handleSubmit} disabled={loading} />
          </form>
        </div>
      </main>
    </>
  );
}
